---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: true

- name: Update repository cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
