---
- name: add users
  user:
    name: "{{ item.username }}"
    shell: "/bin/bash"
    createhome: true
    comment: "Created with Ansible"
    groups: "{{ item.groups }}"
    password: "{{ item.password }}"
    generate_ssh_key: true
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
  with_items: "{{ users }}"

- name: Upload SSH keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.public_keys | join('\n') }}"
    state: present
  with_items: "{{ users }}"
